# Generated by Django 3.1.7 on 2022-01-19 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text_pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='textpagetranslation',
            name='seo_content',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Контент'),
        ),
        migrations.AddField(
            model_name='textpagetranslation',
            name='seo_title',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Заголовок'),
        ),
    ]
