# Generated by Django 3.1.7 on 2022-03-25 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text_pages', '0003_auto_20220119_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='textpage',
            name='menu_position',
            field=models.CharField(choices=[('buyers', 'Покупателям'), ('about', 'О компании')], default='buyers', max_length=500, verbose_name='Раздел в меню'),
        ),
    ]
