# Generated by Django 3.1.7 on 2021-12-15 13:20

import catalog.models.category
import catalog.models.product
import ckeditor_uploader.fields
import colorfield.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields
import parler.fields
import parler.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=500, unique=True, verbose_name='SLUG')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Сортировка')),
                ('cover', models.FileField(blank=True, default=None, null=True, upload_to=catalog.models.category.get_upload_path, verbose_name='Обложка категории')),
                ('is_active', models.BooleanField(default=False, verbose_name='Категория активна')),
                ('on_main', models.BooleanField(default=False, verbose_name='Выводить на главной')),
                ('on_transactions', models.BooleanField(default=False, verbose_name='Выводить на транзакционных страницах')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='catalog.category', verbose_name='Родительская категория')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Справочник категорий',
                'ordering': ('order',),
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hex', colorfield.fields.ColorField(blank=True, default=None, max_length=32, null=True, verbose_name='HEX код цвета')),
                ('display_on_main', models.BooleanField(default=False, verbose_name='Отображать в фильтрах')),
            ],
            options={
                'verbose_name': 'Цвет',
                'verbose_name_plural': 'Справочник цветов',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_on_main', models.BooleanField(default=False, verbose_name='Отображать в фильтрах')),
            ],
            options={
                'verbose_name': 'Материал',
                'verbose_name_plural': 'Справочник материалов',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(blank=True, null=True, upload_to='', verbose_name='Видео')),
                ('slug', models.SlugField(max_length=500, unique=True, verbose_name='URL')),
                ('is_active', models.BooleanField(default=True, verbose_name='Включен')),
                ('order', models.PositiveIntegerField(default=catalog.models.product.autoincrement, verbose_name='Сортировка')),
                ('length', models.PositiveIntegerField(default=0, verbose_name='Длина')),
                ('width', models.PositiveIntegerField(default=0, verbose_name='Ширина')),
                ('weight', models.PositiveIntegerField(default=0, verbose_name='Вес в граммах')),
                ('height', models.PositiveIntegerField(default=0, verbose_name='Высота')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='Розничная цена')),
                ('price_with_sale', models.PositiveIntegerField(default=0, verbose_name='Розничная цена со скидкой')),
                ('is_new', models.BooleanField(default=False, verbose_name='Новый')),
                ('amount', models.PositiveIntegerField(default=0, verbose_name='Оставшееся количество')),
                ('category', models.ManyToManyField(blank=True, related_name='category_products', to='catalog.Category', verbose_name='Категория')),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='catalog.color', verbose_name='Цвет')),
                ('colors', models.ManyToManyField(blank=True, related_name='_product_colors_+', to='catalog.Product', verbose_name='Цвета')),
                ('materials', models.ManyToManyField(blank=True, related_name='products', to='catalog.Material', verbose_name='Материалы')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
                'ordering': ['order'],
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ProductTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default=None, max_length=500, null=True, unique=True, verbose_name='slug')),
                ('is_active', models.BooleanField(default=False, verbose_name='Отображать')),
            ],
            options={
                'verbose_name': 'Тэг',
                'verbose_name_plural': 'Тэги',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_on_main', models.BooleanField(default=False, verbose_name='Отображать в фильтрах')),
            ],
            options={
                'verbose_name': 'Размер',
                'verbose_name_plural': 'Размеры',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ProductGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('size', models.BigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Размер файла в байтах')),
                ('file', models.FileField(upload_to=catalog.models.product.get_upload_path, verbose_name='Файл')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Порядок')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.product', verbose_name='Изображние товара')),
            ],
            options={
                'verbose_name': 'Галлерея товаров',
                'verbose_name_plural': 'Галлерея товаров',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='seo_tags',
            field=models.ManyToManyField(blank=True, related_name='seo_products', to='catalog.ProductTag', verbose_name='SEO тэги'),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalog.size', verbose_name='Размер'),
        ),
        migrations.AddField(
            model_name='product',
            name='sizes',
            field=models.ManyToManyField(blank=True, related_name='_product_sizes_+', to='catalog.Product', verbose_name='Размеры'),
        ),
        migrations.AddField(
            model_name='product',
            name='suggested_products',
            field=models.ManyToManyField(blank=True, related_name='_product_suggested_products_+', to='catalog.Product', verbose_name='Вам может понравиться'),
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='products', to='catalog.ProductTag', verbose_name='Тэги'),
        ),
        migrations.AddField(
            model_name='product',
            name='total_look',
            field=models.ManyToManyField(blank=True, related_name='_product_total_look_+', to='catalog.Product', verbose_name='Дополни образ'),
        ),
        migrations.CreateModel(
            name='SizeTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('size', models.CharField(max_length=255, verbose_name='Размер')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='catalog.size')),
            ],
            options={
                'verbose_name': 'Размер Translation',
                'db_table': 'catalog_size_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ProductTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('delivery', models.TextField(blank=True, null=True, verbose_name='Варианты и сроки доставки')),
                ('measurements', models.TextField(blank=True, null=True, verbose_name='Обмеры')),
                ('model_measurements', models.TextField(blank=True, null=True, verbose_name='Обмеры модели')),
                ('care', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Уход')),
                ('composition', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Состав и характеристики')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='catalog.product')),
            ],
            options={
                'verbose_name': 'Продукт Translation',
                'db_table': 'catalog_product_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ProductTagTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('text', models.CharField(max_length=100, verbose_name='Текст тэга')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='catalog.producttag')),
            ],
            options={
                'verbose_name': 'Тэг Translation',
                'db_table': 'catalog_producttag_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='MaterialTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(blank=True, max_length=500, null=True, verbose_name='Название')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='catalog.material')),
            ],
            options={
                'verbose_name': 'Материал Translation',
                'db_table': 'catalog_material_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ColorTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(blank=True, max_length=500, null=True, verbose_name='Название')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='catalog.color')),
            ],
            options={
                'verbose_name': 'Цвет Translation',
                'db_table': 'catalog_color_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='CategoryTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(blank=True, max_length=500, null=True, verbose_name='Название')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='catalog.category')),
            ],
            options={
                'verbose_name': 'Категория Translation',
                'db_table': 'catalog_category_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
