# Generated by Django 3.1.7 on 2021-12-16 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sizes',
        ),
        migrations.CreateModel(
            name='TradeOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(default=0, verbose_name='Количество')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активен')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_offers', to='catalog.product', verbose_name='Продукт')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='size_trade_offers', to='catalog.size', verbose_name='Размер')),
            ],
            options={
                'verbose_name': 'Торговое предложение',
                'verbose_name_plural': 'Торговые предложения',
            },
        ),
    ]
