# Generated by Django 3.1.7 on 2022-01-24 14:12

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20211216_1337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producttranslation',
            name='care',
        ),
        migrations.RemoveField(
            model_name='producttranslation',
            name='composition',
        ),
        migrations.RemoveField(
            model_name='producttranslation',
            name='delivery',
        ),
        migrations.RemoveField(
            model_name='producttranslation',
            name='measurements',
        ),
        migrations.AddField(
            model_name='producttranslation',
            name='composition_and_care',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Состав и уход'),
        ),
    ]
