# Generated by Django 3.1.7 on 2022-02-01 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20220124_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Артикул'),
        ),
    ]
