# Generated by Django 3.1.7 on 2022-02-02 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_product_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='major_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='major_products', to='catalog.category', verbose_name='Главная категория'),
        ),
    ]
