# Generated by Django 3.1.7 on 2022-02-03 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20220202_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='display_in_menu',
            field=models.BooleanField(default=False, verbose_name='Выводить в меню'),
        ),
    ]
