# Generated by Django 3.1.7 on 2021-12-15 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('last_activity', models.DateTimeField(verbose_name='Дата активности')),
                ('username', models.CharField(blank=True, max_length=256, null=True, verbose_name='Email')),
                ('status', models.CharField(choices=[('not_completed', 'Не закончена'), ('completed', 'Перешло на оплату'), ('payed', 'Оплачено')], default='not_completed', max_length=50, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Корзина',
                'verbose_name_plural': 'Корзины',
                'ordering': ['-last_activity'],
            },
        ),
        migrations.CreateModel(
            name='ProductInCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Количество в корзине')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='cart.cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='catalog.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Продукт в заказе',
                'verbose_name_plural': 'Продукты в заказах',
                'ordering': ('id',),
            },
        ),
    ]
