# Generated by Django 3.1.7 on 2021-12-16 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20211216_1337'),
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeOfferInCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Количество в корзине')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='cart.cart')),
                ('trade_offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='catalog.tradeoffer', verbose_name='Торговое предложение')),
            ],
            options={
                'verbose_name': 'Продукт в заказе',
                'verbose_name_plural': 'Продукты в заказах',
                'ordering': ('id',),
            },
        ),
        migrations.DeleteModel(
            name='ProductInCart',
        ),
    ]
