# Generated by Django 3.1.7 on 2022-05-11 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_auto_20211216_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='status',
            field=models.CharField(choices=[('not_completed', 'Не закончена'), ('completed', 'Перешло на оформление'), ('payed', 'Оформлена')], default='not_completed', max_length=50, verbose_name='Статус'),
        ),
    ]
