# Generated by Django 3.1.7 on 2022-01-26 11:49

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mainbanner',
            options={'ordering': ('order',), 'verbose_name': 'Главный баннер', 'verbose_name_plural': 'Главные баннеры'},
        ),
        migrations.AlterModelOptions(
            name='secondbanner',
            options={'ordering': ('order',), 'verbose_name': 'Второй баннер', 'verbose_name_plural': 'Вторые баннеры'},
        ),
        migrations.AlterField(
            model_name='mainbannertranslation',
            name='subtitle',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=500, verbose_name='Подзаголовок баннера'),
        ),
    ]
