# Generated by Django 3.1.7 on 2023-04-12 15:42

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import parler.fields
import parler.models
import utils.models.banners


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0003_emailforcontacts'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainPageBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Название баннера')),
                ('link', models.CharField(blank=True, max_length=2000, verbose_name='Ссылка с баннера')),
                ('desktop_image', models.FileField(blank=True, upload_to=utils.models.banners.get_upload_path, verbose_name='Изображение для десктопа')),
                ('mobile_image', models.FileField(blank=True, upload_to=utils.models.banners.get_upload_path, verbose_name='Изображение для мобильных')),
            ],
            options={
                'verbose_name': 'Главная страница',
                'verbose_name_plural': 'Главные страницы',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='MainPageBannerTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(blank=True, max_length=500, null=True, verbose_name='Заголовок баннера')),
                ('button_text', models.CharField(blank=True, max_length=200, null=True, verbose_name='Текст кнопки баннера')),
                ('subtitle', ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=500, verbose_name='Подзаголовок баннера')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='utils.mainpagebanner')),
            ],
            options={
                'verbose_name': 'Главная страница Translation',
                'db_table': 'utils_mainpagebanner_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
