# Generated by Django 3.1.7 on 2023-04-12 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0004_mainpagebanner_mainpagebannertranslation'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainpagebanner',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Активный'),
        ),
    ]
