# Generated by Django 3.1.7 on 2021-12-15 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время заказа')),
                ('country', models.CharField(default='не указана', max_length=90, null=True, verbose_name='Страна')),
                ('city', models.CharField(default='не указан', max_length=189, null=True, verbose_name='Город')),
                ('zip_code', models.CharField(default='не указан', max_length=18, null=True, verbose_name='Индекс')),
                ('street', models.CharField(default='не указана', max_length=150, null=True, verbose_name='Улица')),
                ('house', models.CharField(default='не указан', max_length=150, null=True, verbose_name='Дом')),
                ('house_building', models.CharField(default='не указан', max_length=150, null=True, verbose_name='Корпус')),
                ('apartment', models.CharField(default='не указана', max_length=150, null=True, verbose_name='Квартира')),
                ('first_name', models.CharField(max_length=150, null=True, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=150, null=True, verbose_name='Фамилия')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
                ('phone', models.CharField(max_length=17, verbose_name='Телефон')),
                ('comment', models.TextField(blank=True, max_length=1000, verbose_name='Комментарий')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('send-to-delivery', 'Передан в доставку'), ('dostavlen-klientu', 'Доставлен клиенту'), ('cancel-other', 'Отменен'), ('complete', 'Выполнен'), ('vozvrat', 'Возврат'), ('assembling', 'Комплектуется'), ('prepayed', 'Предоплата поступила'), ('notpaydelivery', 'Доставка не оплачана'), ('change', 'Обмен'), ('assembling-complete', 'Укомплектован'), ('delivering', 'Доставляется'), ('redirect', 'Доставка перенесена'), ('return-delivery', 'Вовзврат отправления'), ('no-call', 'Недозвон'), ('no-product', 'Нет в наличии'), ('delyvery-did-not-suit', 'Не устроила доставка'), ('question', 'Остались вопросы')], default='new', max_length=100, verbose_name='Статус')),
                ('payment_status', models.CharField(choices=[('not-paid', 'Не оплачено'), ('paid', '100% оплата'), ('fail', 'Ошибка'), ('vozvrat', 'Возврат')], default='not-paid', max_length=100, verbose_name='Статус оплаты')),
                ('payment_type', models.CharField(choices=[('card', 'Онлайн'), ('upon_receipt', 'Наличные при получении')], default='card', max_length=100, verbose_name='Тип оплаты')),
                ('pickup_type', models.CharField(choices=[('unknown', 'Другое'), ('pickup', 'Самовывоз')], default='unknown', max_length=100, verbose_name='Способ доставки')),
                ('cost', models.PositiveIntegerField(default=0, verbose_name='Стоимость заказа')),
                ('delivery_cost', models.PositiveIntegerField(default=0, verbose_name='Стоимость доставки')),
                ('discount_value', models.PositiveIntegerField(default=0, verbose_name='Скидка руб')),
                ('summary_cost', models.PositiveIntegerField(default=0, verbose_name='Общая стоимость')),
                ('delivery_agree', models.BooleanField(blank=True, default=False, null=True, verbose_name='Согласие на международную доставку')),
                ('locale', models.CharField(default='ru', max_length=20, verbose_name='Локализация')),
                ('paid_amount', models.CharField(blank=True, max_length=20, null=True, verbose_name='Сумма оплаты')),
                ('paid_currency', models.CharField(blank=True, max_length=10, null=True, verbose_name='Валюта оплаты')),
                ('payment_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата и время оплаты')),
                ('weight', models.PositiveIntegerField(default=0, verbose_name='Вес посылки')),
                ('cart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='cart.cart')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductInOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.PositiveIntegerField(default=0, verbose_name='Цена')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('color', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='catalog.color', verbose_name='Цвет')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_products', to='orders.order', verbose_name='Заказ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_in_orders', to='catalog.product', verbose_name='Товар')),
                ('size', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='catalog.size', verbose_name='Размер')),
            ],
            options={
                'verbose_name': 'Товар в заказе',
                'verbose_name_plural': 'Товары в заказе',
            },
        ),
    ]
