# Generated by Django 3.1.7 on 2022-02-10 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='body_size',
            field=models.CharField(blank=True, max_length=128, verbose_name='Обхват талии'),
        ),
        migrations.AddField(
            model_name='order',
            name='bust_size',
            field=models.CharField(blank=True, max_length=128, verbose_name='Обхват груди'),
        ),
        migrations.AddField(
            model_name='order',
            name='height',
            field=models.CharField(blank=True, max_length=128, verbose_name='Рост'),
        ),
        migrations.AddField(
            model_name='order',
            name='hip_size',
            field=models.CharField(blank=True, max_length=128, verbose_name='Обхват бедер'),
        ),
        migrations.AddField(
            model_name='order',
            name='weeding_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата свадьбы'),
        ),
    ]
