# Generated by Django 3.1.7 on 2022-02-18 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20220210_1814'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationForFitting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=256, verbose_name='Имя и фамилия')),
                ('phone', models.CharField(max_length=17, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='Email')),
                ('date_of_wedding', models.DateField(blank=True, null=True, verbose_name='Дата свадьбы')),
                ('comment', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Комментарий')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('time', models.DateTimeField(verbose_name='Время примерки')),
                ('service_type', models.CharField(choices=[(8765543, 'Примерка коротких платьев'), (8765556, 'Повторная примерка коротких платьев'), (8765563, 'Примерка длинных платьев'), (8765582, 'Повторная примерка длинных платьев'), (8765595, 'Примерка сшитого платья на заказ'), (8765051, 'Записаться на примерку')], max_length=50, verbose_name='Тип примерки')),
                ('external_id', models.CharField(blank=True, max_length=256, null=True, verbose_name='Внешний ид')),
                ('external_hash', models.CharField(blank=True, max_length=256, null=True, verbose_name='Внешний hash')),
            ],
            options={
                'verbose_name': 'Запись на примерку',
                'verbose_name_plural': 'Записи на примерку',
            },
        ),
    ]
