# Generated by Django 3.1.7 on 2022-07-22 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20220221_1108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery_agree',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_type',
        ),
        migrations.RemoveField(
            model_name='order',
            name='pickup_type',
        ),
    ]
